# Generated by Django 6.1 on 2026-08-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_alter_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks'), ('Drinks', 'Drinks'), ('Cool Drinks', 'Cool Drinks'), ('Desserts', 'Desserts'), ('Combos', 'Combos'), ('Main Food', 'Main Food'), ('Side Dishes', 'Side Dishes')], max_length=50),
        ),
    ]
